export const quests = [
    'High-five 5 people',
    'Get 3 people to hydrate',
    'Take 3 selfies with a dog (or one with 3 dogs)',
    'Take a photo before and after you compliment someone on their outfit',
    'Make a trade with someone',
    'Whistle on a blade of grass (or fail miserably)',
    'Get someone’s number. Doesn’t have to be a phone number',
    'Arm wrestle someone you know who will win. Be extra confident.',
    'Compliment someone’s belt specifically.',
    'Compliment someone’s left shoe/boot specifically.',
    'Find a really cool rock',
    'Text someone you love them in a language neither of you speak',
    'Text someone a photo of you flipping them off',
    'Make someone laugh. By force if necessary.',
    'Text someone that you left the oven on, someone who doesn’t live near you. Make no big deal out of it.',
    'Hug a tree',
    'Give someone headpats',
    'Walk up to someone, and with a serious face say “uwu”',
    'Text someone in only song lyrics',
    'Borrow a hat (with consent) and take a photo wearing it',
    'Find someone with the same name as you (or give someone your name)',
    'Get someone to tell you their favourite festival memory',
    'Find someone with a matching accessory and take a photo together',
    'Ask someone to teach you a phrase in another language',
    'Give a high five to someone wearing sunglasses',
    'Get someone to make a silly face and take a picture',
    'Find someone with an interesting tattoo and ask about its story (they\'re allowed to lie about it)',
    'Ask someone to take a photo of you doing a funny pose',
    'Come up with a random object that represents your personality, and explain why',
    'Recite an ad you can remember. Lie and make one up if you can\'t remember any',
    'Stage a dramatic reading of someone\'s text message',
    'Get up to three people in a group chat to tell them something unimportant, then leave',
    'Come up with a piece of legislation that would make the world a better place. Now pick the worst politician for the job',
    'Come up with the worst Castlefest related pick up line.',
    // 'Propose to someone (doesn’t have to be to someone you know)',
    // 'Take a picture with an exotic animal',
    // 'Photobomb someone, have the photo be sent to you',
    // 'Act out an epic death on the LARP field',
    // 'Get the autograph of a famous wizard',
    // 'Tell someone about the ‘Fitness gram pacer test’',
    // 'Tell a story about a random topic, it must take at least 5 minutes',
    // 'Save humanity (repeatable)',
    // 'Text or call someone as if you have something very important to say, only to tell them something extremely underwhelming',
    // 'Tell someone you’ve been meaning to contact them about their car’s extended warranty',
    // 'Pick 3 blue flowers',
    // 'Pick 3 red flowers',
    // 'Pick 3 yellow flowers',
    // 'Ascend / Achieve a higher plane',
    // 'Write a magic spell. Decide the unfortunate cost of casting this spell',
    // 'Give a tree love',
    // 'Swipe someone right',
    // 'Cross swords with someone',
    // 'Be cringe',
    // 'Design a bug for your favourite game',
    // 'Find a delectable treat for yourself',
];

export const groupQuests = [
    'Get someone to text you back. Fastest wins',
    'Organise a group hug',
    'Draw a line in the path and get 3 people to jump over it',
    'Get 3 (or more) people to do the wave with you',
    'Invent a new handshake that involves all group members',
    'Tell a short story where each person adds 2 words at a time',
    'Think of a random object that represents each member\'s personality and explain why',
    'Pretend you’re holding a rope over the path and get 3 people to jump over it',
    'Find a clone of yourself. Closest match wins.',
];